#!/bin/bash

#first of all, need to set nut MODE
sed -i -e 's/^\s*MODE\s*=.*/MODE=standalone/g' /etc/nut/nut.conf

#create upsd.conf
touch /etc/nut/upsd.conf
echo "LISTEN 127.0.0.1 3493" > /etc/nut/upsd.conf
echo "MAXCONN 256" >> /etc/nut/upsd.conf
